{% set name = "snouty-viewer" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snouty-viewer-{{ version }}.tar.gz
  sha256: 0c59c9a659d8793148d6d749123340e0543960587ea189e19470390c3e523271

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - tifffile

test:
  imports:
    - snouty_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aelefebv/snouty-viewer
  summary: A plugin to visualize and convert Snouty data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aelefebv
    - goanpeca
    - jaimergp
